"use client";

import { ArrowUpRight, ChevronDown, Info } from 'lucide-react';
import { Popover } from 'radix-ui';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuCheckboxItem, DropdownMenuItem, DropdownMenuSeparator } from './ui/dropdown-menu';
import s from './analytics-controls.module.css';

export function ArrowAction({label,onClick,disabled=false,primary=false,className=''}:{label:string;onClick:()=>void;disabled?:boolean;primary?:boolean;className?:string}) {
 return <button type="button" className={`${s.arrowAction} ${primary?s.primaryArrow:''} ${className}`} aria-label={label} title={label} disabled={disabled} onClick={onClick}><ArrowUpRight size={17} aria-hidden="true"/></button>;
}

const notes:Record<string,string>={
 'Risk Score Distribution':'See how members are spread across risk score ranges. Each bar shows a share of members with a score. The median is the middle score; 90% of scored members are at or below the 90th percentile. Members without a score are left out.',
 'HCC Prevalence':'See the five most common HCCs in your population. Each slice shows how many members have that condition. A member with more than one condition can appear in several slices.',
 'Geographical Distribution':'See the five counties with the most members, based on where they live. Average RAF gives more weight to members with more months of coverage and includes only valid scores. Small groups and totals that could reveal them are hidden.',
 'Suspect Opportunities':'See the five practices with the most members whose suspected conditions could add to their risk score. The percentage shows how many eligible members in each practice have at least one opportunity, based on your current filters. Each member is counted once, even if they have several suspects.',
 'Risk Adjustment Opportunity Analysis':'The rows rank the displayed opportunity categories by suspect count. Marker positions compare each count with the largest category. Percentages use all findings in the selected population. The total at the top includes all possible additions, including categories not shown. Possible overcoding and data checks are counted separately.',
 'Suspect Prioritization Matrix':'Larger bubbles mean more members. Quick Win groups have higher expected RAF gain and a higher chance of closure; Big Bet groups have higher gain with a lower chance. Easy Gain groups have lower gain with a higher chance, while Watchlist groups have lower gain and a lower chance. Low means below 35%, Medium is 35% to below 65%, and High is 65% or more. Higher-value groups start at a 0.14 expected RAF gain, based on estimated condition impact and supporting evidence. Select a bubble or quadrant to see its suspects. Conditions still need clinical confirmation.',
 'HCC Recapture Status':'See which conditions from last year have been documented again this year and which are still missing. Each cell shows the share confirmed for that condition within the selected health network or month. The latest month comes first. A dash means the value is unavailable or the group is too small to show.',
 'Year-over-Year RAF Change':'Compare 2025 and 2026 scores for the same continuing members, using the same months of coverage. Model Impact isolates the change in model on the prior-year clinical profile; Captured Conditions adds newly recorded HCCs, while Open Opportunities subtracts prior-year HCCs not yet recaptured. These steps reconcile to the 2026 score. The cohort uses modeled annual scores; actual results depend on member diagnoses and model coefficients.',
 'Cumulative Suspect Identification & Closure':'Suspects are counted once when identified. Larger detection runs add more suspects; closures follow as evidence is resolved, sometimes in later months. Total Closed includes confirmed and unsupported findings. Closed — HCC Confirmed is included in Total Closed. Still Open is Total Identified minus Total Closed. Both lines add up from January through each month. Network and provider filters use the same history.',
 'SDOH & Population Risk Stratification':'Each circle represents a county; larger circles mean more members. Select a circle to see its details; the yellow ring marks your selection. The horizontal axis shows average risk score. The vertical axis shows the share of eligible members with a recorded food, housing or transport need. Dashed lines mark the middle values across all eligible counties. Social Vulnerability means higher recorded social needs with a lower average risk score. Complex Care Needs is higher on both measures. Clinical Complexity has a higher risk score with fewer recorded social needs, while Lower Complexity is lower on both measures. Average scores use valid scores weighted by months of coverage. Social needs and race come from member records. Small groups are hidden.',
 'Suspected HCCs':'See suspected findings grouped by their mapped HCC. Several findings can point to the same HCC, so the totals count findings rather than unique codes. These conditions still need confirmation. The Conditions List includes findings with an HCC mapping.',
 'Condition Prevalence':'See the 10 most common conditions. Larger areas mean more members with that condition. Members can appear in more than one group. Select a condition to see the related members and suspects.',
 'Chronic Condition Recapture':'See how many of last year’s conditions have been documented again this year. The recapture rate is the share confirmed again through the reporting month, counting each condition once per member.',
 'County RAF Benchmarking':'Compare the 10 counties with the highest average RAF against the population average. Both use the same score basis and give more weight to members with more months of coverage. Missing scores are left out, and counties with too few members to display safely are hidden.',
 'County Risk Benchmarking':'Compare the 10 counties with the highest average score against the population average. Both use the same score basis and give more weight to members with more months of coverage. Missing scores are left out, and counties with too few members to display safely are hidden.',
 'Geographic Suspect Opportunities':'See the five counties with the most members who have possible additions to their risk score. Each member is counted once in their county. Percentages compare these five counties with one another.',
 'Provider Capture & Recapture Rates':'See the 10 providers with the most open suspects. Capture rate shows the share of identified suspects that were confirmed. Recapture rate shows the share of last year’s conditions documented again this year. Both reflect the members assigned to the selected provider.',
 'Baseline Risk Score Composition':'This planning breakdown assigns 36% of the baseline score to age and member details, 53% to health conditions and 11% to combined conditions. These are assumed shares, not a breakdown calculated using CMS model coefficients.',
 'Risk Score Scenario Comparison':'Compare scores for the same members, using the same weighting for months of coverage. Potential shows what the score could reach if eligible suspected conditions are confirmed. Baseline, submitted and accepted scores each represent a different set of conditions; potential is not an accepted payment score.',
 'Risk-Adjusted Revenue Bridge':'Start with the value of the selected positive opportunities over eligible covered months. Phase-In Reduction removes value outside the assumed effective period. Review / Evidence Reduction accounts for the share reviewed and each finding’s likelihood of confirmation. Realization Reduction removes the share not expected to contribute to revenue. Hover over a reduction to see its signed amount. Potential overcoding exposure is separate and is not deducted. The dollar basis and score impacts are forecast assumptions.',
 'Cumulative RA Revenue Forecast':'Estimated incremental RA revenue accumulates across eligible months. The three-month phase-in brings one third of the expected opportunity into value in each of the first three eligible months; Immediate applies all of it from the first eligible month. This prospective assumption does not represent cash receipt dates or retroactive payments. Shortening the forecast does not rewrite earlier months. Conservative and Optimistic move with your Expected assumptions, using the same selected opportunities and coverage.',
 'Revenue Scenario Comparison':'All three scenarios use the same selected opportunities, covered-member share, eligible months, phase-in and dollar basis. Conservative uses two thirds of Expected review coverage, seven ninths of its payment realization, and the lower evidence-support estimate. Optimistic uses 120% of Expected coverage and Expected realization divided by 90%, each capped at 100%, with the upper support estimate. Evidence Support is weighted by score impact. The range is a sensitivity comparison, not a statistical confidence interval. Possible overcoding is reported separately.',
 'AI Detection Performance':'Of 135 AI flags, 108 were supported by evidence; this is precision. The AI found 108 of 120 known conditions; this is recall. Across 1,000 checks, it correctly flagged 108 conditions, raised 27 unsupported flags, missed 12 conditions and correctly left 853 unflagged. Population filters do not change this comparison.',
 'AI-Assisted Review Performance':'Compare reviews completed with and without AI assistance across 200 charts, with 100 charts in each group. Precision, recall and F1 are calculated separately for each group. AI helps interpret evidence; clinical rules and confirmation requirements still apply.',
 'AI Performance Comparison':'Compare results from the same reference group, which is separate from your filtered population. Review time is the average time per chart. AI assistance keeps the same clinical rules and evidence requirements.',
};

export function ChartInfo({title,description,context}:{title:string;description?:string;context?:string}) {
 const copy=description||notes[title]||(title==='Year-over-Year Risk Score Change'?notes['Year-over-Year RAF Change']:undefined)||(/trend$/i.test(title)?'Monthly RAF estimates for the selected population, from January through the reporting month. Baseline and Potential follow the selected reporting month. Submitted and Accepted are shown only up to August; Potential includes remaining suspected HCCs. The monthly profile is modeled using published risk-adjustment guidance, rather than imported plan or CMS payment history.':undefined);
 if(!copy)return null;
 return <Popover.Root><Popover.Trigger asChild><button type="button" className={s.info} aria-label={`About ${title}`}><Info size={16}/></button></Popover.Trigger><Popover.Portal><Popover.Content className={s.popover} sideOffset={8} align="end" collisionPadding={18}><strong>{title}</strong>{context&&<p>{context}</p>}<p>{copy}</p><Popover.Close className={s.close}>Close</Popover.Close><Popover.Arrow fill="white"/></Popover.Content></Popover.Portal></Popover.Root>;
}

export function ConditionSelect({options,value,onChange}:{options:string[];value:string[];onChange:(value:string[])=>void}) {
 return <div className={s.condition}><span>Disease Family</span><DropdownMenu><DropdownMenuTrigger asChild><button type="button" className={s.select} aria-label="Disease Family">{value.length===0?'All disease families':value.length===1?value[0]:`${value.length} disease families`}<ChevronDown size={14}/></button></DropdownMenuTrigger><DropdownMenuContent className={s.menu} align="end"><DropdownMenuItem onSelect={()=>onChange([])}>All disease families</DropdownMenuItem><DropdownMenuSeparator/>{options.map(name=><DropdownMenuCheckboxItem key={name} checked={value.includes(name)} onSelect={e=>e.preventDefault()} onCheckedChange={checked=>onChange(checked?[...value,name]:value.filter(v=>v!==name))}>{name}</DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu></div>;
}
