"use client";

import { ArrowUpRight, ChevronDown, Info } from 'lucide-react';
import { Popover } from 'radix-ui';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuCheckboxItem, DropdownMenuItem, DropdownMenuSeparator } from './ui/dropdown-menu';
import s from './analytics-controls.module.css';

export function ArrowAction({label,onClick,disabled=false,primary=false,className=''}:{label:string;onClick:()=>void;disabled?:boolean;primary?:boolean;className?:string}) {
 return <button type="button" className={`${s.arrowAction} ${primary?s.primaryArrow:''} ${className}`} aria-label={label} title={label} disabled={disabled} onClick={onClick}><ArrowUpRight size={17} aria-hidden="true"/></button>;
}

const notes:Record<string,string>={
 'Risk Score Distribution':'See how members are spread across risk score ranges. Each bar shows a share of members with a score. The median is the middle score; 90% of scored members are at or below the 90th percentile. Members without a score are left out.',
 'HCC Prevalence':'See the five most common HCCs in your population. Each slice shows how many members have that condition. A member with more than one condition can appear in several slices.',
 'Geographical Distribution':'See the five counties with the most members, based on where they live. Average RAF gives more weight to members with more months of coverage and includes only valid scores. Small groups and totals that could reveal them are hidden.',
 'Suspect Opportunities':'See the five practices with the most members whose suspected conditions could add to their risk score. The percentage shows how many eligible members in each practice have at least one opportunity, based on your current filters. Each member is counted once, even if they have several suspects.',
 'Risk Adjustment Opportunity Analysis':'The five rows rank possible additions by suspect count. Marker positions compare each count with the largest category. Percentages use all findings in the selected population. The total at the top includes possible additions only. Possible overcoding and data checks are counted separately.',
 'Suspect Prioritization Matrix':'Larger bubbles mean more members. Their position shows the expected RAF gain and how likely the suspects are to close. Low means below 35%, Medium is 35% to below 65%, and High is 65% or more. Higher-value groups start at a 0.14 expected RAF gain, based on estimated condition impact and supporting evidence. Select a bubble or quadrant to see its suspects. Conditions still need clinical confirmation.',
 'HCC Recapture Status':'See which conditions from last year have been documented again this year and which are still missing. Each cell shows the share confirmed for that condition within the selected health network or month. The latest month comes first. A dash means the value is unavailable or the group is too small to show.',
 'Continuing Member Risk Score Change':'Compare 2025 and 2026 scores for members enrolled in both years who have a score in each year. Both years use the same score basis and weighting for months of coverage. Read the chart from left to right: 2025 score, Model Lift, Captured Conditions, Open Opportunities and 2026 score. Each step shows its contribution to the overall score change.',
 'Cumulative Suspect Outcomes':'Compare all health networks or select one network. Each point adds up all runs from the start of the year through that month. New suspects are counted once when identified. Closing a suspect does not reduce Total Identified. Still Open is Total Identified minus Total Closed. Total Closed includes both confirmed conditions and suspects the evidence did not support. The confirmed count is part of Total Closed, counting each confirmed condition once per member.',
 'SDOH & Population Risk Stratification':'Each circle represents a county; larger circles mean more members. Select a circle to see its details; the yellow ring marks your selection. The horizontal axis shows average risk score. The vertical axis shows the share of eligible members with a recorded food, housing or transport need. Dashed lines mark the middle values across all eligible counties; the shaded area is above both. Average scores use valid scores weighted by months of coverage. Social needs and race come from member records. Small groups are hidden.',
 'Suspected HCCs':'See suspected findings grouped by their mapped HCC. Several findings can point to the same HCC, so the totals count findings rather than unique codes. These conditions still need confirmation. The Conditions List includes findings with an HCC mapping.',
 'Condition Prevalence':'See the 10 most common conditions. Larger areas mean more members with that condition. Members can appear in more than one group. Select a condition to see the related members and suspects.',
 'Chronic Condition Recapture':'See how many of last year’s conditions have been documented again this year. The recapture rate is the share confirmed again through the reporting month, counting each condition once per member.',
 'County RAF Benchmarking':'Compare the 10 counties with the highest average RAF against the population average. Both use the same score basis and give more weight to members with more months of coverage. Missing scores are left out, and counties with too few members to display safely are hidden.',
 'County Risk Benchmarking':'Compare the 10 counties with the highest average score against the population average. Both use the same score basis and give more weight to members with more months of coverage. Missing scores are left out, and counties with too few members to display safely are hidden.',
 'Geographic Suspect Opportunities':'See the five counties with the most members who have possible additions to their risk score. Each member is counted once in their county. Percentages compare these five counties with one another.',
 'Provider Capture & Recapture Rates':'See the 10 providers with the most open suspects. Capture rate shows the share of identified suspects that were confirmed. Recapture rate shows the share of last year’s conditions documented again this year. Both reflect the members assigned to the selected provider.',
 'Baseline Risk Score Composition':'This planning breakdown assigns 36% of the baseline score to age and member details, 53% to health conditions and 11% to combined conditions. These are assumed shares, not a breakdown calculated using CMS model coefficients.',
 'Risk Score Scenario Comparison':'Compare scores for the same members, using the same weighting for months of coverage. Potential shows what the score could reach if eligible suspected conditions are confirmed. Baseline, submitted and accepted scores each represent a different set of conditions; potential is not an accepted payment score.',
 'Risk-Adjusted Revenue Bridge':'The forecast starts with the highest-value eligible addition for each member. It then accounts for the review rate, supporting evidence and payment rate, and subtracts possible overcoding deductions. The dollar amount per RAF point is a forecast assumption. The result is estimated revenue, not an actual CMS payment, and does not include costs.',
 'Cumulative Revenue Projection':'See how estimated additional revenue builds over the forecast period. Expected uses your applied review and payment rates. Conservative and Optimistic use their own rates and evidence assumptions. Additional revenue follows the selected payment timing; coding deductions start in the first month.',
 'Revenue Scenario Comparison':'Compare Conservative, Expected and Optimistic forecasts for the same findings and coverage assumptions. The forecasts use different review rates, payment rates and levels of evidence support. Corrections without a dollar estimate are listed separately. Changing a forecast does not change member diagnoses or submissions.',
 'AI Detection Performance':'Of 135 AI flags, 108 were supported by evidence; this is precision. The AI found 108 of 120 known conditions; this is recall. Across 1,000 checks, it correctly flagged 108 conditions, raised 27 unsupported flags, missed 12 conditions and correctly left 853 unflagged. Population filters do not change this comparison.',
 'AI-Assisted Review Performance':'Compare reviews completed with and without AI assistance across 200 charts, with 100 charts in each group. Precision, recall and F1 are calculated separately for each group. AI helps interpret evidence; clinical rules and confirmation requirements still apply.',
 'AI Performance Comparison':'Compare results from the same reference group, which is separate from your filtered population. Review time is the average time per chart. AI assistance keeps the same clinical rules and evidence requirements.',
};

export function ChartInfo({title,description,context}:{title:string;description?:string;context?:string}) {
 const copy=description||notes[title]||(/trend$/i.test(title)?'Monthly RAF estimates for the selected population, from January through the reporting month. The latest points match the score tiles. Submitted and accepted sets reflect different timing; potential includes remaining suspected HCCs. The monthly profile is modeled using published risk-adjustment guidance, rather than imported plan or CMS payment history.':undefined);
 if(!copy)return null;
 return <Popover.Root><Popover.Trigger asChild><button type="button" className={s.info} aria-label={`About ${title}`}><Info size={16}/></button></Popover.Trigger><Popover.Portal><Popover.Content className={s.popover} sideOffset={8} align="end" collisionPadding={18}><strong>{title}</strong>{context&&<p>{context}</p>}<p>{copy}</p><Popover.Close className={s.close}>Close</Popover.Close><Popover.Arrow fill="white"/></Popover.Content></Popover.Portal></Popover.Root>;
}

export function ConditionSelect({options,value,onChange}:{options:string[];value:string[];onChange:(value:string[])=>void}) {
 return <div className={s.condition}><span>Conditions</span><DropdownMenu><DropdownMenuTrigger asChild><button type="button" className={s.select} aria-label="Opportunity conditions">{value.length===0?'All conditions':value.length===1?value[0]:`${value.length} conditions`}<ChevronDown size={14}/></button></DropdownMenuTrigger><DropdownMenuContent className={s.menu} align="end"><DropdownMenuItem onSelect={()=>onChange([])}>All conditions</DropdownMenuItem><DropdownMenuSeparator/>{options.map(name=><DropdownMenuCheckboxItem key={name} checked={value.includes(name)} onSelect={e=>e.preventDefault()} onCheckedChange={checked=>onChange(checked?[...value,name]:value.filter(v=>v!==name))}>{name}</DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu></div>;
}
