"use client";
import { useState } from "react";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, LoaderCircle } from "lucide-react";
import { MonthlyTrend, PrevalenceTiles, ComparisonPlot } from "./report-visuals";
import { Button } from "./ui/button";
import { DataGrid, Empty, Panel, Status } from "./shared";
import { RiskRecapture, useRiskContext } from "./risk-ui";
import { api, label, num } from "@/lib/api";
import { formatRiskScore, scoreBasisLabels, downloadRiskJson } from "@/lib/risk-client";
import type { ScoreBasis } from "@/lib/risk-types";
import type { User } from "@/lib/types";

type Aggregate = { value: number | null; numerator: number | null; denominator: number; members: number; run_ids: string[]; reason?: string };
type AnalyticsResult = { stale: boolean; definition: string; weighting: string; scope_members: number; monthly: { month: string; value: number; numerator: number; denominator: number }[]; category_prevalence: { category: string; members: number; denominator: number; member_ids: string[] }[]; stages: (Aggregate & { basis: ScoreBasis; stale_members: number; movement: { matched_members: number; before: Aggregate; after: Aggregate; delta: number | null; method: string; unmatched_members: number } | null })[]; comparison: { status: string; reason?: string; prior_config_id?: string; matched_members?: number; before?: Aggregate; after?: Aggregate; raw_change?: number | null; attribution?: { factor: string; value: number | null }[]; attribution_method?: string; excluded_prior_only?: number; excluded_current_only?: number; members?: { member_id: string; name: string; prior_run_id: string; current_run_id: string; delta: number }[] } };
export function RiskAnalytics({ user, initialTab = "movement" }: { user: User; initialTab?: string }) {
  const context = useRiskContext();
  const [tab, setTab] = useState(initialTab);
  const [prior, setPrior] = useState("");
  const [category, setCategory] = useState("");
  const results = useQuery({ queryKey: ["risk", "analytics", user.id, context.configId, context.basis, prior], queryFn: () => api<AnalyticsResult>(`/risk/analytics?${new URLSearchParams({ config_id: context.configId, basis: context.basis, ...(prior ? { prior_config_id: prior } : {}) })}`), enabled: !!context.configId });
  const data = results.data;
  const selectedCategory = data?.category_prevalence.find((item) => item.category === category);
  const comparison = data?.comparison;
  return <div className="risk-workspace"><div className="risk-tabs" role="tablist" aria-label="Risk analytics views">{[["movement", "Risk and stage movement"], ["conditions", "Condition prevalence"], ["recapture", "Annual recapture"], ["period", "Actual period comparison"]].map(([value, name]) => <button key={value} role="tab" aria-selected={tab === value} onClick={() => setTab(value)}>{name}</button>)}</div>
    {tab !== "recapture" && context.permissions.includes("export") && <div className="risk-profile-toolbar"><span /><Button variant="outline" disabled={!data || !!results.error} onClick={() => downloadRiskJson({ configuration: context.configuration, score_basis: context.basis, prior_config_id: prior || null, analytics: data }, `risk-analytics-${context.configId}-${context.basis}.json`)}>Export retained analytics</Button></div>}
    {tab === "recapture" ? <RiskRecapture user={user} /> : results.isPending ? <div className="risk-loading"><LoaderCircle className="animate-spin" size={18} />Reading stored risk analytics…</div> : results.error ? <Empty title="Risk analytics unavailable" description={results.error.message} /> : data ? <>
      {data.stale && <div className="risk-notice">Some retained results have changed inputs. Stale member counts remain visible beside their score stages.</div>}
      {tab === "movement" ? <>
        <Panel title="Monthly calculated risk" subtitle={`${scoreBasisLabels[context.basis]} · ${data.weighting}`}>
          <MonthlyTrend values={data.monthly} />
          <details className="risk-disclosure"><summary>Monthly values and denominators</summary><div className="table-scroll"><table className="risk-table"><thead><tr><th>Month</th><th>Raw score</th><th>Score numerator</th><th>Member-month denominator</th></tr></thead><tbody>{data.monthly.map((item) => <tr key={item.month}><td>{item.month}</td><td>{formatRiskScore(item.value)}</td><td>{formatRiskScore(item.numerator, 6)}</td><td>{num(item.denominator)}</td></tr>)}</tbody></table></div></details>
        </Panel>
        <Panel title="Separate score stages" subtitle="Stage differences use the matched member cohort; acceptance does not establish eligibility or payment."><div className="table-scroll"><table className="risk-table"><thead><tr><th>Score basis</th><th>Portfolio value</th><th>Members / months</th><th>Matched movement</th><th>Unmatched / stale</th></tr></thead><tbody>{data.stages.map((stage) => <tr key={stage.basis}><td><Button variant="ghost" size="sm" onClick={() => context.choose(context.configId, stage.basis)}>{scoreBasisLabels[stage.basis]}</Button><small>{stage.reason}</small></td><td className="risk-number">{formatRiskScore(stage.value)}</td><td>{num(stage.members)} members<small>{num(stage.denominator)} member-months</small></td><td>{formatRiskScore(stage.movement?.delta, 3, true)}<small>{stage.movement ? `${stage.movement.matched_members} matched members` : "Initial basis"}</small></td><td>{stage.movement?.unmatched_members ?? "—"} unmatched<small>{num(stage.stale_members)} stale</small></td></tr>)}</tbody></table></div><p className="risk-helper padded">{data.definition}</p></Panel>
      </> : tab === "conditions" ? <>
        <Panel title="Condition prevalence at a glance" subtitle="Distinct member prevalence in the selected model"><PrevalenceTiles items={data.category_prevalence} selected={category} onSelect={setCategory} /></Panel>
        {selectedCategory && <Panel title={`${selectedCategory.category} · contributing members`} subtitle={`${num(selectedCategory.members)} distinct members`}><DataGrid rows={selectedCategory.member_ids.map((id) => ({ id }))} columns={[{ accessorKey: "id", header: "Member ID" }, { id: "open", header: "Retained score profile", cell: ({ row }) => <Link href={context.href(`/members/${row.original.id}?tab=Risk+profile`)}>Open risk profile<ArrowUpRight size={13} /></Link> }]} /></Panel>}
        <Panel title="Retained model category prevalence" subtitle="Each category counts distinct members under the selected model and score basis."><DataGrid rows={data.category_prevalence.map((item) => ({ ...item, id: item.category }))} onRow={(item) => setCategory(item.category)} searchLabel="Search model categories…" columns={[{ accessorKey: "category", header: "Model category" }, { accessorKey: "members", header: "Distinct members" }, { accessorKey: "denominator", header: "Scored-member denominator" }, { id: "open", header: "Contributing members", cell: ({ row }) => <Button variant="ghost" size="sm" onClick={() => setCategory(row.original.category)}>Inspect cohort<ArrowUpRight size={13} /></Button> }]} /></Panel>
      </> : <>
        <div className="risk-profile-toolbar"><label className="risk-field-label">Prior configuration<select aria-label="Prior period configuration" value={prior} onChange={(event) => setPrior(event.target.value)}><option value="">Choose an actual prior input period</option>{context.configurations.filter((item) => item.id !== context.configId && item.program === context.configuration?.program).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{user.screens.includes("scenarios") && <Button variant="outline" asChild><Link href={context.href("/scenarios")}>Fixed-input model comparison<ArrowUpRight size={13} /></Link></Button>}</div>
        {comparison?.status === "available" ? <><div className="risk-metrics three">{[["Prior comparable value", comparison.before?.value], ["Current comparable value", comparison.after?.value], ["Raw period change", comparison.raw_change]].map(([title, value]) => <div className="risk-metric" key={String(title)}><span>{title}</span><strong>{formatRiskScore(value as number | null, 3, title === "Raw period change")}</strong><small>{comparison.matched_members} matched members</small></div>)}</div><Panel title="Period change bridge" subtitle={comparison.attribution_method}><ComparisonPlot rows={[{ name: "Matched cohort", before: comparison.before?.value, after: comparison.after?.value }]} leftLabel="Prior period" rightLabel="Current period" format={value => formatRiskScore(value)} /><div className="table-scroll"><table className="risk-table"><thead><tr><th>Retained attribution</th><th>Score-point change</th></tr></thead><tbody>{comparison.attribution?.map((item) => <tr key={item.factor}><td>{item.factor}</td><td>{formatRiskScore(item.value, 3, true)}</td></tr>)}</tbody></table></div><div className="risk-panel-foot"><span>{comparison.excluded_prior_only || 0} prior-only members excluded · {comparison.excluded_current_only || 0} current-only members excluded</span><Status value={comparison.status} /></div></Panel><Panel title="Matched-member evidence" subtitle="Retained prior and current runs support the displayed comparison."><DataGrid rows={(comparison.members || []).map((item) => ({ ...item, id: item.member_id }))} columns={[{ accessorKey: "name", header: "Member" }, { accessorKey: "delta", header: "Raw change", cell: ({ getValue }) => formatRiskScore(Number(getValue()), 3, true) }, { id: "prior", header: "Prior inputs", cell: ({ row }) => <Link href={context.href(`/members/${row.original.member_id}?tab=Scoring+inputs&run=${row.original.prior_run_id}`)}>Inspect prior snapshot<ArrowUpRight size={13} /></Link> }, { id: "current", header: "Current inputs", cell: ({ row }) => <Link href={context.href(`/members/${row.original.member_id}?tab=Scoring+inputs&run=${row.original.current_run_id}`)}>Inspect current snapshot<ArrowUpRight size={13} /></Link> }]} /></Panel></> : <Empty title={label(comparison?.status || "not_selected")} description={comparison?.reason || "Calculate both actual input periods before comparing their matched cohort."} />}
      </>}
    </> : null}
  </div>;
}
