#!/usr/bin/env python3
"""Independent reference generation: runs stock CMS CLI, never imports Perform+.

Run with the model environment after scripts/model_assets.py install. Synthetic
PERSON/diagnosis inputs here are authored test fixtures, not clinical records.
The output JSON is frozen evidence, not generated by the adapter under test.
"""
import argparse
from collections import defaultdict
import csv
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tempfile

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]


def write(path, columns, rows):
    with path.open('w', newline='') as stream:
        writer = csv.DictWriter(stream, fieldnames=columns)
        writer.writeheader()
        writer.writerows(rows)


def generate(assets, target):
    manifest = json.loads((ROOT / 'apps/api/app/risk_models/assets.json').read_text())
    cases = json.loads((HERE / 'cases.json').read_text())
    grouped = defaultdict(list)
    for case in cases:
        grouped[case['package']].append(case)
    evidence = {'method': 'Separate invocation of unchanged official CMS CLI; no application adapter imports',
                'python': platform.python_version(), 'cases_sha256': hashlib.sha256((HERE / 'cases.json').read_bytes()).hexdigest(),
                'packages': {}, 'cases': {}}
    for package, cohort in grouped.items():
        spec = manifest['packages'][package]
        original = assets / package
        for name, digest in spec['files'].items():
            if hashlib.sha256((original / name).read_bytes()).hexdigest() != digest:
                raise RuntimeError(f'Unexpected official asset bytes: {package}/{name}')
        with tempfile.TemporaryDirectory(prefix='cms-independent-reference-') as tmp:
            stage = Path(tmp) / 'stock'
            shutil.copytree(original, stage)
            module = spec['model_module']
            folder = stage / 'software' / module / 'data/input/user_defined'
            persons, diagnoses, ndcs, procedures = [], [], [], []
            for index, case in enumerate(cohort, 1):
                person = dict(case['person'], ID=index)
                year, month, day = person['DOB'].split('-')
                person['DOB'] = f'{month}/{day}/{year}' if module == 'CMS_HCC_v28' else year + month + day
                persons.append(person)
                for code in case['diagnoses']:
                    diagnosis = {'ID': index, 'ICD10': code}
                    if module == 'HHS_HCC':
                        diagnosis['DIAGNOSIS_SERVICE_DATE'] = case['service_date'].replace('-', '')
                    diagnoses.append(diagnosis)
                ndcs.extend({'ID': index, 'NDC': code} for code in case.get('ndc', []))
                procedures.extend({'ID': index, 'HCPCS': code} for code in case.get('hcpcs', []))
            if module == 'HHS_HCC':
                write(folder / 'PERSON.csv', ['ID', 'DOB', 'SEX', 'AGE_LAST', 'METAL', 'CSR_INDICATOR', 'ENROLDURATION'], persons)
                write(folder / 'DIAGNOSES.csv', ['ID', 'ICD10', 'DIAGNOSIS_SERVICE_DATE'], diagnoses)
                write(folder / 'NDC.csv', ['ID', 'NDC'], ndcs)
                write(folder / 'HCPCS.csv', ['ID', 'HCPCS'], procedures)
            else:
                write(folder / 'beneficiaries.csv', ['ID', 'DOB', 'SEX', 'OREC', 'LTIMCAID', 'NEMCAID'] if module == 'CMS_HCC_v28' else ['ID', 'DOB', 'SEX', 'OREC', 'ESRD'], persons)
                write(folder / 'diagnoses.csv', ['ID', 'ICD10'], diagnoses)
            command = [sys.executable, f'software/{module}/transform.py']
            run = subprocess.run(command, cwd=stage, env=dict(os.environ, PYTHONDONTWRITEBYTECODE='1', PYTHONHASHSEED='0'), capture_output=True, text=True, timeout=300)
            if run.returncode:
                raise RuntimeError(run.stderr[-3000:] or run.stdout[-3000:])
            output = next((stage / 'software' / module / 'data/output').glob('*.csv'))
            rows = list(csv.DictReader(output.open(encoding='utf-8-sig')))
            if len(rows) != len(cohort):
                raise RuntimeError('Reference input/output inventories differ')
            evidence['packages'][package] = {'asset_sha256': manifest['archives'][spec['archive']]['sha256'], 'tree_sha256': spec['tree_sha256'],
                                             'command': ['python', command[1]], 'output_filename': output.name,
                                             'output_sha256': hashlib.sha256(output.read_bytes()).hexdigest(), 'count': len(rows)}
            for row in rows:
                case = cohort[int(float(row['ID'])) - 1]
                evidence['cases'][case['id']] = {'scores': {k: float(v) for k, v in row.items() if k.startswith(('SCORE_', 'CSR_ADJUSTED_SCORE')) and v},
                                                'flags': {k: v for k, v in row.items() if not k.startswith(('SCORE_', 'CSR_ADJUSTED_SCORE')) and k != 'ID' and v not in ('0', '0.0', '')}}
            print(f'{package}: {len(rows)} official reference rows')
    target.write_text(json.dumps(evidence, indent=2, sort_keys=True) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--assets', type=Path, default=ROOT / '.local/model-assets')
    parser.add_argument('--output', type=Path, default=HERE / 'expected.json')
    args = parser.parse_args()
    generate(args.assets, args.output)
