"""Regenerate the EDS reporting cohort from the shared population roster."""
import json
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from apps.api.app import florida_population, population_expansion, provider_hierarchy, analytics_experience

state=json.loads((ROOT/'seed/demo.json').read_text())
florida_population.migrate(state)
population_expansion.expand(state)
members=sorted(state['members'],key=lambda m:m['id'])
# Preserve the original EDS sampling fraction: 240 roster members per 10,000.
size=round(len(members)*.024)
rows=[]
for index in range(size):
    member=members[index*len(members)//size]
    hierarchy=provider_hierarchy.identity(member)
    rows.append(dict(id=member['id'],name=member['name'],providerId=member['provider_id'],
        provider=hierarchy['provider'],network=hierarchy['network'],group=hierarchy['group'],
        contract=analytics_experience.contract_for(member)))
body='// Generated by scripts/generate_eds_population.py from the shared roster.\n'
body+=f'export const EDS_POPULATION_SIZE = {len(members)};\n'
body+='export const EDS_POPULATION = '+json.dumps(rows,separators=(',',':'),ensure_ascii=False)+';\n'
(ROOT/'apps/web/src/lib/eds-population.ts').write_text(body)
print(f'EDS cohort: {size} of {len(members)} roster members; six encounters per service year.')
